### DISCUSSION TITLE
Set up list of sensors to find critical temp + humidity

### DISCUSSION THREAD

**Discussion by TheRealWaldo** [TheRealWaldo/ha-optimal-humidity#172] [Ideas]
With a list of sensors that groups themselves by room and by location in that room, ha-optimal-humidity could identify the critical temperature/humidity/pressure/mold risk automatically.

```
# Example configuration.yaml entry

sensor:
  - platform: optimal_humidity
    rooms:
      - test_optimal_humidity:
           name: "Optimal Humidity"
           type: optimal_humidity
           sensors:
              - corner:
                - sensor.indoor_temp
                - sensor.indoor_humidity
                - sensor.indoor_pressure
              - window: 
                - sensor.critical_temp
```
