### DISCUSSION TITLE
Sensor shows no data

### DISCUSSION THREAD

**Discussion by NGLocanovic** [TheRealWaldo/ha-optimal-humidity#179] [Q&A] [answered]
## Version of the custom_component
2.0.3

## Configuration

```yaml

sensor:
  - platform: optimal_humidity
    sensors:
      test_optimal_humidity:
        name: "Optimale Luftfeuchtigkeit"
        type: optimal_humidity
        indoor_temp_sensor: sensor.lumi_lumi_weather_4ee65b04_temperature
        indoor_humidity_sensor: sensor.lumi_lumi_weather_4ee65b04_humidity
        critical_temp_sensor: sensor.lumi_lumi_weather_4ee65b04_temperature
        indoor_pressure_sensor: sensor.lumi_lumi_weather_4ee65b04_pressure

```

## Describe the bug
After placing the sensor into the configuration.yaml file and restarting, it still does not show any data.
The Temperature/humindity sensors have data.

## Debug log
I did not get Logs to work :(

![image](https://user-images.githubusercontent.com/8858043/207740867-2badf4d9-8d56-4a16-a9c8-ad10feafd4f5.png)

Tempsensor:
![image](https://user-images.githubusercontent.com/8858043/207741250-e4fcac59-3e79-41a5-8ce4-b49933a585cb.png)
![image](https://user-images.githubusercontent.com/8858043/207741313-43d927f4-b064-4ac5-aa5c-87a2884802f7.png)
![image](https://user-images.githubusercontent.com/8858043/207741336-2289d37c-038b-4afe-9746-3ecdf904dd57.png)
